/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.stockclem.view;

import co.edu.sena.stockclem.controller.ArticleController;
import co.edu.sena.stockclem.controller.CategoryController;
import co.edu.sena.stockclem.controller.IArticleController;
import co.edu.sena.stockclem.controller.ICategoryController;
import co.edu.sena.stockclem.controller.IPresentationController;
import co.edu.sena.stockclem.controller.ISupplierController;
import co.edu.sena.stockclem.controller.PresentationController;
import co.edu.sena.stockclem.controller.SupplierController;
import co.edu.sena.stockclem.model.Article;
import co.edu.sena.stockclem.model.Category;
import co.edu.sena.stockclem.model.Presentation;
import co.edu.sena.stockclem.model.Supplier;
import javax.swing.JOptionPane;
import co.edu.sena.stockclem.utils.MessageUtils;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolle Melendez
 */
public class JFrameArticle extends javax.swing.JFrame {
    private final IPresentationController presentationController = new PresentationController();
    private final ICategoryController categoryController = new CategoryController();
    private final ISupplierController supplierController = new SupplierController();
    private final IArticleController articleController = new ArticleController();
    int xMouse;
    int yMouse;

    /**
     * Creates new form JFrameArticle
     */
    public JFrameArticle() {
        initComponents();
        fillTable();
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelCloseWindow = new javax.swing.JPanel();
        jLabelCloseWindow = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldIName = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabelphoto = new javax.swing.JLabel();
        jLabelTechnicalSheet = new javax.swing.JLabel();
        jLabelIdPresentation = new javax.swing.JLabel();
        jLabelIdCategory = new javax.swing.JLabel();
        jLabelIdSupplier = new javax.swing.JLabel();
        jTextFieldPhoto = new javax.swing.JTextField();
        jTextFielTechicalSheet = new javax.swing.JTextField();
        jComboBoxIdSupplier = new javax.swing.JComboBox<>();
        jComboBoxIdPresentation = new javax.swing.JComboBox<>();
        jComboBoxIdCategory = new javax.swing.JComboBox<>();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticle = new javax.swing.JTable();
        jLabelBackground = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Article");

        jPanel1.setPreferredSize(new java.awt.Dimension(780, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCloseWindow.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCloseWindow.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabelCloseWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/stockclem/view/Icono de Home.png"))); // NOI18N
        jLabelCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseWindowLayout = new javax.swing.GroupLayout(jPanelCloseWindow);
        jPanelCloseWindow.setLayout(jPanelCloseWindowLayout);
        jPanelCloseWindowLayout.setHorizontalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanelCloseWindowLayout.setVerticalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelCloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelTitle.setFont(new java.awt.Font("Roboto Condensed Black", 1, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("TABLA DE ARTICULOS");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 780, 30));

        jLabelId.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelId.setText("ID:");
        jPanel1.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabelName.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelName.setText("NOMBRE:");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelCantidad.setText("CANTIDAD:");
        jPanel1.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jTextFieldIName.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jTextFieldIName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldINameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, -1));

        jTextFieldQuantity.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jTextFieldQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, -1));

        jTextFieldId.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 220, -1));

        jLabelphoto.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelphoto.setText("FOTO:");
        jPanel1.add(jLabelphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabelTechnicalSheet.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelTechnicalSheet.setText("FICHA:");
        jPanel1.add(jLabelTechnicalSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabelIdPresentation.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelIdPresentation.setText("ID PRESENTACION:");
        jPanel1.add(jLabelIdPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jLabelIdCategory.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelIdCategory.setText("ID CATEGORIA:");
        jPanel1.add(jLabelIdCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabelIdSupplier.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabelIdSupplier.setText("ID PROVEEDOR:");
        jPanel1.add(jLabelIdSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jTextFieldPhoto.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jTextFieldPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhotoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 220, -1));

        jTextFielTechicalSheet.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jTextFielTechicalSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielTechicalSheetActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielTechicalSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 190, -1));

        jPanel1.add(jComboBoxIdSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 190, -1));

        jPanel1.add(jComboBoxIdPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 190, -1));

        jPanel1.add(jComboBoxIdCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 190, -1));

        jButtonInsert.setBackground(new java.awt.Color(0, 255, 0));
        jButtonInsert.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonInsert.setText("INSERTAR");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 130, -1));

        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 255));
        jButtonUpdate.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setEnabled(false);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 150, -1));

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 110, -1));

        jButtonClear.setBackground(new java.awt.Color(0, 204, 204));
        jButtonClear.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonClear.setText("LIMPIAR");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 110, -1));

        jTableArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArticleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArticle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 730, 120));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/stockclem/view/Fondo para menu opcion1.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        // EVENTO PARA MOVER LA PESTAÑA
        int xPosition = evt.getXOnScreen();
        int yPosition = evt.getYOnScreen();

        this.setLocation(xPosition - xMouse, yPosition - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        // EVENTO COMPLEMETNARIO PARA MOVER LA PESTAÑA
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jLabelCloseWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseClicked
        //BOTON PARA CERRAR
        int option = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de salir", "CONFIRMAR", JOptionPane.YES_NO_OPTION);

        if(option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabelCloseWindowMouseClicked

    private void jLabelCloseWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseEntered
        // BOTON EFECTO HOVER
        jPanelCloseWindow.setBackground(Color.CYAN);
    }//GEN-LAST:event_jLabelCloseWindowMouseEntered

    private void jLabelCloseWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseExited
        // TBOTON PARA EFECTO HOVER DE SALIDA
        jPanelCloseWindow.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabelCloseWindowMouseExited

    private void jTextFieldINameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldINameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldINameActionPerformed

    private void jTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantityActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jTextFieldPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhotoActionPerformed

    private void jTextFielTechicalSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielTechicalSheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielTechicalSheetActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // BOTONN PARA INSERTAR
            try {
            Article article = new Article();
            article.setName(jTextFieldIName.getText());
            article.setQuantity(Integer.parseInt(jTextFieldQuantity.getText()));
            article.setPhoto(jTextFieldPhoto.getText());
            article.setTechnicalSheet(jTextFielTechicalSheet.getText());
            article.setIdPresentation((Presentation) jComboBoxIdPresentation.getSelectedItem());
            article.setIdCategory((Category) jComboBoxIdCategory.getSelectedItem());
            article.setIdSupplier((Supplier) jComboBoxIdSupplier.getSelectedItem());
            articleController.insert(article);
            MessageUtils.showInfoMessage("Salida añadida exitosamente");
            clear();
            fillTable();
            
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al insertar la salida..."
                    + e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // BOTONN PARA ACTUALIZAR
            try {
            Article article = new Article();
            article.setName(jTextFieldIName.getText());
            article.setQuantity(Integer.parseInt(jTextFieldQuantity.getText()));
            article.setPhoto(jTextFieldPhoto.getText());
            article.setTechnicalSheet(jTextFielTechicalSheet.getText());
            article.setIdPresentation((Presentation) jComboBoxIdPresentation.getSelectedItem());
            article.setIdCategory((Category) jComboBoxIdCategory.getSelectedItem());
            article.setIdSupplier((Supplier) jComboBoxIdSupplier.getSelectedItem());
            articleController.update(article);
            MessageUtils.showInfoMessage("Articulo añadida exitosamente");
            clear();
            fillTable();
            
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al actualizar el articulo..."
                    + e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        
        //BOTON PARA ELIMINAR
        try {
            int option = JOptionPane.showConfirmDialog(rootPane,"Estas seguro de eliminar?",
                "CONFIRMAR", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                articleController.delete(Long.valueOf(jTextFieldId.getText()));
                MessageUtils.showInfoMessage("Articulo eliminado correctamente...");
                fillTable();
            }
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("HUBO UN ERROR al eliminar el articulo..." + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // BOTON PARA LIMPIAR
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTableArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArticleMouseClicked
        // EVENTO PARA EL CLICK EN LA TABLA
        int rowSelected = jTableArticle.getSelectedRow();
        if (rowSelected != -1) {
            Long idArticle = Long.valueOf(jTableArticle.getValueAt(rowSelected, 0).toString());
            try {
                Article ar = articleController.findById(idArticle);
                jTextFieldId.setText(String.valueOf(ar.getIdArticle()));
                jTextFieldIName.setText(ar.getName());
                jTextFieldQuantity.setText(String.valueOf(ar.getQuantity()));
                jTextFieldPhoto.setText(ar.getPhoto());
                jTextFielTechicalSheet.setText(ar.getTechnicalSheet());
                jComboBoxIdPresentation.getModel().setSelectedItem(ar.getIdPresentation());
                jComboBoxIdCategory.getModel().setSelectedItem(ar.getIdCategory());
                jComboBoxIdSupplier.getModel().setSelectedItem(ar.getIdSupplier());
                
            } catch (Exception e) {
                MessageUtils.showErrorMessage("ERROR al usar el evento de click"
                    + e.getMessage());
            }
        }
        jButtonInsert.setEnabled(false);
        jButtonDelete.setEnabled(true);
        jButtonUpdate.setEnabled(true);
    }//GEN-LAST:event_jTableArticleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameArticle().setVisible(true);
            }
        });
    }
    
    
    public void clear(){
        jTextFieldId.setText("");
        jTextFieldIName.setText("");
        jTextFieldQuantity.setText("");
        jTextFieldPhoto.setText("");
        jTextFielTechicalSheet.setText("");
        jComboBoxIdCategory.setSelectedIndex(-1);
        jComboBoxIdPresentation.setSelectedIndex(-1);
        jComboBoxIdSupplier.setSelectedIndex(-1);
        jButtonInsert.setEnabled(true);
        jButtonDelete.setEnabled(false);
        jButtonUpdate.setEnabled(false);
    }
    
    
    public void fillTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTableArticle.setModel(model);
            model.addColumn("Id");
            model.addColumn("Nombre");
            model.addColumn("Cantidad");
            model.addColumn("Foto");
            model.addColumn("Ficha Tecnica");
            model.addColumn("Nueva presentación");
            model.addColumn("Nueva categoria");
            model.addColumn("Nuevo proveedor");

            String[] rows = new String[8];
            List<Article> article = articleController.findAll();
            for (Article a : article) {
                rows[0] = String.valueOf(a.getIdArticle());
                rows[1] = a.getName();
                rows[2] = String.valueOf(a.getQuantity());
                rows[3] = a.getPhoto();
                rows[4] = a.getTechnicalSheet();
                rows[5] = String.valueOf(a.getIdPresentation().getIdPresentation());
                rows[6] = a.getIdCategory().getName();
                rows[7] = a.getIdSupplier().getName();
                model.addRow(rows);
            }
            jButtonInsert.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDelete.setEnabled(false);
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al llenar la tabla..."
                    + e.getMessage());
        }
    }
    
        public void fillComboBox() {
        try {
            // Listar todas las categorias foraneas
            List<Presentation> presentations = presentationController.findAll();
            List<Category> categorys = categoryController.findAll();
            List<Supplier> suppliers = supplierController.findAll();
            
            // Crear modelos
            DefaultComboBoxModel presentationsModel = new DefaultComboBoxModel();
            DefaultComboBoxModel categorysModel = new DefaultComboBoxModel();
            DefaultComboBoxModel suppliersModel = new DefaultComboBoxModel();
            
            // Setear modelos
            jComboBoxIdPresentation.setModel(presentationsModel);
            jComboBoxIdCategory.setModel(categorysModel);
            jComboBoxIdSupplier.setModel(suppliersModel);
            
            // Agregar datos y establecer primera posición por default
            presentationsModel.addAll(presentations);
            categorysModel.addAll(categorys);
            suppliersModel.addAll(suppliers);
            jComboBoxIdPresentation.setSelectedIndex(0);
            jComboBoxIdCategory.setSelectedIndex(0);
            jComboBoxIdSupplier.setSelectedIndex(0);
            
            
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxIdCategory;
    private javax.swing.JComboBox<String> jComboBoxIdPresentation;
    private javax.swing.JComboBox<String> jComboBoxIdSupplier;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCloseWindow;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdCategory;
    private javax.swing.JLabel jLabelIdPresentation;
    private javax.swing.JLabel jLabelIdSupplier;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTechnicalSheet;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelphoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCloseWindow;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArticle;
    private javax.swing.JTextField jTextFielTechicalSheet;
    private javax.swing.JTextField jTextFieldIName;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldPhoto;
    private javax.swing.JTextField jTextFieldQuantity;
    // End of variables declaration//GEN-END:variables
}
