package co.edu.sena.stockclem.view;

import javax.swing.JFrame;

/**
 *
 * @author Esteban Colorado Vargas
 */
public class JFrameMenu extends javax.swing.JFrame {
    int xMouse;
    int yMouse;

    /**
     * Creates new form JFrameMenu
     */
    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jLabellogo = new javax.swing.JLabel();
        jButtonArticle = new javax.swing.JButton();
        jButtonCategory = new javax.swing.JButton();
        jButtonEntry = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonPerson = new javax.swing.JButton();
        jButtonPresentation = new javax.swing.JButton();
        jButtonsSupplier = new javax.swing.JButton();
        jButtonUnit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jLabelBackGround = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabellogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/stockclem/view/Logo Stock Clem.png"))); // NOI18N
        jPanelBackGround.add(jLabellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 270, 470));

        jButtonArticle.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonArticle.setText("ARTICULOS");
        jButtonArticle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonArticle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArticleActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, -1));

        jButtonCategory.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonCategory.setText("CATEGORIAS");
        jButtonCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoryActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, -1));

        jButtonEntry.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonEntry.setText("ENTRADAS");
        jButtonEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntryActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 210, -1));

        jButtonExit.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonExit.setText("SALIDAS");
        jButtonExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, -1));

        jButtonPerson.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonPerson.setText("PERSONAS");
        jButtonPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonPerson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 210, -1));

        jButtonPresentation.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonPresentation.setText("PRESENTACIONES");
        jButtonPresentation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonPresentation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPresentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPresentationActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 210, -1));

        jButtonsSupplier.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonsSupplier.setText("PROVEEDORES");
        jButtonsSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonsSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonsSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsSupplierActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonsSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 210, -1));

        jButtonUnit.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonUnit.setText("UNIDADES");
        jButtonUnit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 41), 3));
        jButtonUnit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnitActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 210, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenid@ a STOCK-CLEM!");
        jPanelBackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 510, -1));

        jButtonClose.setBackground(new java.awt.Color(255, 0, 51));
        jButtonClose.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClose.setText("CERRAR PROGRAMA");
        jButtonClose.setBorderPainted(false);
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 450, -1));

        jLabelBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/stockclem/view/BackGround para Menu.png"))); // NOI18N
        jPanelBackGround.add(jLabelBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelBackGround.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        // EVENTO PARA MOVER LA PESTAÑA
        int xPosition = evt.getXOnScreen();
        int yPosition = evt.getYOnScreen();

        this.setLocation(xPosition - xMouse, yPosition - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        // EVENTO COMPLEMENTARIO PARA MOVER LA PESTAÑA
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // BOTON PARA CERRAR PROGRAMA
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArticleActionPerformed
        // BOTON PARA MOSTRAR FRAME ARTICLE
        showWindow(new JFrameArticle());
    }//GEN-LAST:event_jButtonArticleActionPerformed

    private void jButtonCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoryActionPerformed
        // BOTON PARA MOSTRAR FRAME CATEGORIA
        showWindow(new JFrameCategory());
    }//GEN-LAST:event_jButtonCategoryActionPerformed

    private void jButtonEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntryActionPerformed
        // BOTON PARA MOSTRAR FRAME ENTRADA
        showWindow(new JFrameEntry());
    }//GEN-LAST:event_jButtonEntryActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // BOTON PARA MOSTRAR FRAME SALIDA
        showWindow(new JFrameExit());
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonPresentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPresentationActionPerformed
        // BOTON PARA MOSTRAR FRAME PRESENTACION
        showWindow(new JFramePresentation());
    }//GEN-LAST:event_jButtonPresentationActionPerformed

    private void jButtonPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonActionPerformed
        // BOTON PARA MOSTRAR FRAME PERSONA
        showWindow(new JFramePerson());
    }//GEN-LAST:event_jButtonPersonActionPerformed

    private void jButtonsSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsSupplierActionPerformed
        // BOTON PARA MOSTRAR FRAME PROVEEDOR
        showWindow(new JFrameSupplier());
    }//GEN-LAST:event_jButtonsSupplierActionPerformed

    private void jButtonUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnitActionPerformed
        // BOTON PARA MOSTRAR FRAME UNIDAD
        showWindow(new JFrameUnit());
    }//GEN-LAST:event_jButtonUnitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }
    
    public void showWindow(JFrame frameToShow) {
        frameToShow.setVisible(true);
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArticle;
    private javax.swing.JButton jButtonCategory;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonEntry;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPerson;
    private javax.swing.JButton jButtonPresentation;
    private javax.swing.JButton jButtonUnit;
    private javax.swing.JButton jButtonsSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackGround;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JPanel jPanelBackGround;
    private javax.swing.JPanel jPanelHeader;
    // End of variables declaration//GEN-END:variables
}
