package co.edu.sena.stockclem.view;

import co.edu.sena.stockclem.controller.ArticleController;
import co.edu.sena.stockclem.controller.EntryController;
import co.edu.sena.stockclem.controller.IArticleController;
import co.edu.sena.stockclem.controller.IEntryController;
import co.edu.sena.stockclem.model.Article;
import co.edu.sena.stockclem.model.Entry;
import co.edu.sena.stockclem.utils.ConvertUtils;
import co.edu.sena.stockclem.utils.MessageUtils;
import co.edu.sena.stockclem.utils.SwingUtils;
import java.awt.Color;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * date: 25/04/2025
 * @author Esteban Colorado Vargas
 * objetivo: crear las vistas para la tabla article
 */
public class JFrameEntry extends javax.swing.JFrame {
    private final IArticleController articleController = new ArticleController();
    private final IEntryController entryController = new EntryController();
    int xMouse;
    int yMouse;

    /**
     * Creates new form JFrameArticle
     */
    public JFrameEntry() {
        initComponents();
        fillEntryTable();
        fillEntryCombo();
//        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldIdEntry = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntry = new javax.swing.JTable();
        jButtonClear = new javax.swing.JButton();
        jLabelExpirationDate = new javax.swing.JLabel();
        jLabelIdEntry = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jTextFieldSenaCode = new javax.swing.JTextField();
        jPanelCloseWindow = new javax.swing.JPanel();
        jLabelCloseWindow = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        datePickerDateEnter = new com.github.lgooddatepicker.components.DatePicker();
        jButtonUpdate = new javax.swing.JButton();
        datePickerExpirationDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabelSenaCode = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldObservations = new javax.swing.JTextField();
        jLabelObservations = new javax.swing.JLabel();
        jLabelIdArticle = new javax.swing.JLabel();
        jComboBoxIdArticle = new javax.swing.JComboBox<>();
        jLabelDateEnter = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("TABLA DE ENTRADAS");
        jLabelTitle.setFont(new java.awt.Font("Roboto Condensed Black", 1, 24)); // NOI18N
        jPanelBackGround.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 780, 30));

        jTextFieldIdEntry.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jTextFieldIdEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 190, 30));

        jButtonInsert.setBackground(new java.awt.Color(0, 255, 0));
        jButtonInsert.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonInsert.setText("INSERTAR");
        jButtonInsert.setBorderPainted(false);
        jButtonInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 30));

        jTableEntry.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jTableEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEntryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEntry);

        jPanelBackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 740, 140));

        jButtonClear.setBackground(new java.awt.Color(0, 204, 204));
        jButtonClear.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonClear.setText("LIMPIAR");
        jButtonClear.setBorderPainted(false);
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 130, 30));

        jLabelExpirationDate.setText("FECHA VENCIMIENTO:");
        jLabelExpirationDate.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jLabelExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabelIdEntry.setText("ID:");
        jLabelIdEntry.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jLabelIdEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelQuantity.setText("CANTIDAD:");
        jLabelQuantity.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jLabelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jTextFieldSenaCode.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jTextFieldSenaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, 30));

        jPanelCloseWindow.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCloseWindow.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabelCloseWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/stockclem/view/Icono de Home.png"))); // NOI18N
        jLabelCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseWindowLayout = new javax.swing.GroupLayout(jPanelCloseWindow);
        jPanelCloseWindow.setLayout(jPanelCloseWindowLayout);
        jPanelCloseWindowLayout.setHorizontalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCloseWindowLayout.setVerticalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelBackGround.add(jPanelCloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonDelete.setText("ELIMINAR");
        jButtonDelete.setBorderPainted(false);
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 130, 30));

        datePickerDateEnter.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(datePickerDateEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 190, 30));

        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 255));
        jButtonUpdate.setBorderPainted(false);
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanelBackGround.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 130, 30));

        datePickerExpirationDate.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(datePickerExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 190, 30));

        jLabelSenaCode.setText("CODIGO SENA:");
        jLabelSenaCode.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jLabelSenaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTextFieldQuantity.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jTextFieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 190, 30));

        jTextFieldObservations.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jTextFieldObservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 190, 30));

        jLabelObservations.setText("OBSERVACIONES:");
        jLabelObservations.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jLabelObservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabelIdArticle.setText("NOMBRE ARTICULO:");
        jLabelIdArticle.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jLabelIdArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jComboBoxIdArticle.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jComboBoxIdArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 190, 30));

        jLabelDateEnter.setText("FECHA ENTRADA:");
        jLabelDateEnter.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jPanelBackGround.add(jLabelDateEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/stockclem/view/Fondo para menu opcion1.png"))); // NOI18N
        jPanelBackGround.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelBackGround.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // BOTONN PARA INSERTAR
        try {
            Entry entry = new Entry();
            entry.setSenaCode(jTextFieldSenaCode.getText());
            entry.setDate(ConvertUtils.localDateToDate(datePickerDateEnter.getDate()));
            entry.setExpirationDate(ConvertUtils.localDateToDate(datePickerExpirationDate.getDate()));
            entry.setQuantity(Integer.parseInt(jTextFieldQuantity.getText()));
            entry.setObservations(jTextFieldObservations.getText());
            entry.setIdArticle((Article) jComboBoxIdArticle.getSelectedItem());
            entryController.insert(entry);
            MessageUtils.showInfoMessage("La entrada se ha añadido correctamente...");
            fillTable();
            clear();
            insertDefaultDate();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al insertar la entrada..."
                + e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jTableEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEntryMouseClicked
        // EVENTO PARA EL CLICK EN LA TABLA
        int rowSelected = jTableEntry.getSelectedRow();
        if (rowSelected != -1) {
            Long documentSelected = Long.valueOf(jTableEntry.getValueAt(rowSelected, 0).toString());
            try {
                Entry entry = entryController.findById(documentSelected);
                jTextFieldIdEntry.setText(String.valueOf(documentSelected));
                jTextFieldSenaCode.setText(entry.getSenaCode());
                datePickerDateEnter.setDate(ConvertUtils.dateToLocalDate(entry.getDate()));
                datePickerExpirationDate.setDate(ConvertUtils.dateToLocalDate(entry.getExpirationDate()));
                jTextFieldQuantity.setText(String.valueOf(entry.getQuantity()));
                jTextFieldObservations.setText(entry.getObservations());
                jComboBoxIdArticle.getModel().setSelectedItem(entry.getIdArticle());
            } catch (Exception e) {
                MessageUtils.showErrorMessage("ERROR al usar el evento de click"
                    + e.getMessage());
            }
        }
        jButtonInsert.setEnabled(false);
        jButtonDelete.setEnabled(true);
        jButtonUpdate.setEnabled(true);
    }//GEN-LAST:event_jTableEntryMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // BOTON PARA LIMPIAR
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        // EVENTO PARA MOVER LA PESTAÑA
        int xPosition = evt.getXOnScreen();
        int yPosition = evt.getYOnScreen();

        this.setLocation(xPosition - xMouse, yPosition - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        // EVENTO COMPLEMETNARIO PARA MOVER LA PESTAÑA
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jLabelCloseWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseClicked
        // EVENTO PARA CERRAR EL PROGRAMA
        int option = JOptionPane.showConfirmDialog(rootPane, 
                "Quieres volver a el menu principal?", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        
        if(option == JOptionPane.YES_OPTION) {
            new JFrameMenu().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jLabelCloseWindowMouseClicked

    private void jLabelCloseWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseEntered
        // BOTON EFECTO HOVER
        jPanelCloseWindow.setBackground(Color.CYAN);
    }//GEN-LAST:event_jLabelCloseWindowMouseEntered

    private void jLabelCloseWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseExited
        // TBOTON PARA EFECTO HOVER DE SALIDA
        jPanelCloseWindow.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabelCloseWindowMouseExited

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // BOTON PARA ELIMINAR
        try {
            int option = JOptionPane.showConfirmDialog(rootPane,"Estas seguro de eliminar el empleado?",
                "CONFIRMAR", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                entryController.delete(Long.valueOf(jTextFieldIdEntry.getText()));
                MessageUtils.showInfoMessage("Proovedor eliminado correctamente...");
                fillTable();
            }
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("HUBO UN ERROR al eliminar proovedor..." + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // BOTON PARA ACTUALIZAR
        try {
            Entry entry = new Entry();
            entry.setIdEntry(Long.valueOf(jTextFieldIdEntry.getText()));
            entry.setSenaCode(jTextFieldSenaCode.getText());
            entry.setDate(ConvertUtils.localDateToDate(datePickerDateEnter.getDate()));
            entry.setExpirationDate(ConvertUtils.localDateToDate(datePickerExpirationDate.getDate()));
            entry.setQuantity(Integer.parseInt(jTextFieldQuantity.getText()));
            entry.setObservations(jTextFieldObservations.getText());
            entry.setIdArticle((Article) jComboBoxIdArticle.getSelectedItem());
            entryController.update(entry);
            MessageUtils.showInfoMessage("La entrada se ha actualizado correctamente...");
            fillTable();
            clear();
            insertDefaultDate();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al actualizar la entrada..."
                + e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEntry().setVisible(true);
            }
        });
    }
    
    public void clear() {
        jTextFieldIdEntry.setText("");
        jTextFieldSenaCode.setText("");
        jTextFieldQuantity.setText("");
        datePickerDateEnter.setText("");
        jComboBoxIdArticle.setSelectedIndex(0);
        datePickerExpirationDate.setText("");
        jTextFieldObservations.setText("");
        jButtonInsert.setEnabled(true);
        jButtonDelete.setEnabled(false);
        jButtonUpdate.setEnabled(false);
        jTableEntry.clearSelection();
    }
    
    public void fillEntryTable() {
        try {
            LinkedHashMap<String, Function<Entry, Object>> cols = new LinkedHashMap<>();
            cols.put("ID", e -> String.valueOf(e.getIdEntry()));
            cols.put("Codigo sena", e -> String.valueOf(e.getSenaCode()));
            cols.put("Fecha de entrada", e -> ConvertUtils.dateToString(e.getDate()));
            cols.put("Fecha de vencimiento", e -> ConvertUtils.dateToString(e.getExpirationDate()));
            cols.put("Cantidad", e -> String.valueOf(e.getQuantity()));
            cols.put("Nombre articulo", e -> e.getIdArticle().getName());
            
            SwingUtils.fillTable(jTableEntry, entryController.findAll(), cols);
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ocurrio un error al llenar la tabla " + e.getMessage());
        }
    }
    
    public void fillTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTableEntry.setModel(model);
            model.addColumn("ID");
            model.addColumn("Codigo Sena");
            model.addColumn("Fecha Entrada");
            model.addColumn("Fecha Vencimiento");
            model.addColumn("Cantidad");
            model.addColumn("Nombre Articulo");

            String[] rows = new String[6];
            List<Entry> entries = entryController.findAll();
            for (Entry entry : entries) {
                rows[0] = String.valueOf(entry.getIdEntry());
                rows[1] = entry.getSenaCode();
                rows[2] = ConvertUtils.dateToString(entry.getDate());
                rows[3] = ConvertUtils.dateToString(entry.getExpirationDate());
                rows[4] = String.valueOf(entry.getQuantity());
                rows[5] = entry.getIdArticle().getName();
                model.addRow(rows);
            }
            jButtonInsert.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDelete.setEnabled(false);
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al llenar la tabla..."
                    + e.getMessage());
        }
    }
    
    public void fillEntryCombo() {
        try {
            SwingUtils.fillComboBox(jComboBoxIdArticle, articleController.findAll());
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("ha ocurrido un error al llenar el combo de articulos" +
                                          ex.getMessage());
        }
    }
    
    public void fillComboBox() {
        try {
            List<Article> articles = articleController.findAll();
            DefaultComboBoxModel modelEmployee = new DefaultComboBoxModel();
            jComboBoxIdArticle.setModel(modelEmployee);
            modelEmployee.addAll(articles);
            // Establecer selección vacía inicialmente
            jComboBoxIdArticle.setSelectedIndex(0); // Ningún elemento seleccionado
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }
    
    public void insertDefaultDate() {
        datePickerDateEnter.setDate(LocalDate.now());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePickerDateEnter;
    private com.github.lgooddatepicker.components.DatePicker datePickerExpirationDate;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<Article> jComboBoxIdArticle;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCloseWindow;
    private javax.swing.JLabel jLabelDateEnter;
    private javax.swing.JLabel jLabelExpirationDate;
    private javax.swing.JLabel jLabelIdArticle;
    private javax.swing.JLabel jLabelIdEntry;
    private javax.swing.JLabel jLabelObservations;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelSenaCode;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelBackGround;
    private javax.swing.JPanel jPanelCloseWindow;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEntry;
    private javax.swing.JTextField jTextFieldIdEntry;
    private javax.swing.JTextField jTextFieldObservations;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldSenaCode;
    // End of variables declaration//GEN-END:variables
}
